services:
  - type: web
    name: monadbot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: DEVELOPER_ID
        sync: false
    autoDeploy: true
    healthCheckPath: /health